### ISSUE TITLE
"KeyError: 'reply'" when running bot

### ISSUE THREAD

**Issue by brodymc80** [archmagos-dominus/HourAI#6]
I've configured the bot for use with HuggingFace, but when running the bot I receive the following error:

"bot.py", line 106, in query_hf
    return ret["reply"]
           ~~~^^^^^^^^^
KeyError: 'reply'

Has anyone else experienced this or has any ideas?

**Comment by archmagos-dominus** [comment]
Thank you for bringing this to my attention. I haven't used the HF API in quite some time, so it always flew under the radar when new updates were rolled out. It is fixed now, from what I saw there were a few issues with the requests being sent over to the HugginFace API. If you encounter any other bug, feel free to open another issue.

**Comment by brodymc80** [comment]
> Thank you for bringing this to my attention. I haven't used the HF API in quite some time, so it always flew under the radar when new updates were rolled out. It is fixed now, from what I saw there were a few issues with the requests being sent over to the HugginFace API. If you encounter any other bug, feel free to open another issue.

Hey, thanks very much for taking a look at that so quickly.

I've pulled the new .py file and tried running it again, but I'm getting a new error this time (same line as the previous error).
Not sure if this is my fault or the same issue with a different variable:


```
2022-12-14 13:20:01 ERROR    discord.client Ignoring exception in on_ready
Traceback (most recent call last):
  File "...\Conda\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "...\HourAI-main\bot.py", line 225, in on_ready
    resp = query_hf({'inputs': {'text': 'Hello!'}}, api_endpoint, request_headers)
  File "...\HourAI-main\bot.py", line 106, in query_hf
    return ret["generated_text"]
KeyError: 'generated_text'
```

**Comment by archmagos-dominus** [comment]
Upon further examination it seems that while the API response from HugginFace is of this shape `{'generated_text': " ", 'conversation': " ", 'past_user_inputs': " ", 'warnings': " "}` when it is returning a computed reply, it seems to have a different shape (`{error: " ", "warnings": " "`) when the model is still loading up in their cloud infrastructure. I have added a condition that will give you the 'generated_text' feature when you can get it, and shows you the body of the reply when there is an error.

**Comment by archmagos-dominus** [comment]
Hopefully I did not forget anything this time around blep

**Comment by brodymc80** [comment]
I think it's getting close now, new error 😆
`2022-12-14 22:18:31 ERROR    discord.client Ignoring exception in on_ready`
`Traceback (most recent call last):`
 ` File "...\Conda\lib\site-packages\discord\client.py", line 409, in _run_event`
`    await coro(*args, **kwargs)`
`  File "...\HourAI-main\bot.py", line 235, in on_ready`
`    print("Model loading..." + resp["estimated_time"])`

`TypeError: can only concatenate str (not "float") to str`

**Comment by archmagos-dominus** [comment]
Ok, the type mismatch between the string console log and the float ETA has been fixed I think. I hope it should work without a hitch now (please bear in mind that the model from HF might need a minute to load into their cloud infrastructure before use)

**Comment by brodymc80** [comment]
Hey thanks again. The bot actually output to Discord now, so that's a step in the right direction! However, the output was just the error seen below.

This error occurs both when the bot starts and also when it receives a message from one of the channels noted in 'CHANNELID'.

`2022-12-15 09:15:54 INFO     discord.client logging in using static token
2022-12-15 09:15:55 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: XXX).
Bot starting up...
{'error': 'unknown error', 'warnings': ['There was an inference error: unknown error: can only concatenate str (not "dict") to str']}
Bot ready to go!
{'error': 'unknown error', 'warnings': ['There was an inference error: unknown error: can only concatenate str (not "dict") to str']}`

**Comment by archmagos-dominus** [comment]
I'm afraid I cannot replicate this error on my own system. The only thing that comes to mind is to check the config file and make sure you filled up stuff correctly.

**Comment by brodymc80** [comment]
Ah so it looks like that final issue was due to an error with my model. 
I've tried an existing model and it's working fine.

Thanks for all your help!
